Repository unifystockx/code_compete, pull requests merged in 2020-09, with the labels that each got.

#1 Feature/initial project setup with eslint, jest, prettier
  .eslintignore
  .eslintrc
  .prettierrc
  .tsconfig.json
  README.md
  jest.config.js
  package-lock.json
  package.json
  references.md
  src/niraj/foo.spec.ts
  src/niraj/foo.ts
  src/niraj/readme.md
  src/praveen/readme.md
  src/rajasekhar/readme.md
  src/zulqer/readme.md
Labels: enhancement

#6 #5 - Replace npm with yarn in husky hook
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#10 Niraj:Narcissistic number computation, test coverage implementation
  .gitignore
  .tsconfig.json
  jest.config.js
  package.json
  references.md
  src/niraj/foo.spec.ts
  src/niraj/foo.ts
  src/niraj/narcissisticNumbers.spec.ts
  src/niraj/narcissisticNumbers.ts
Labels: task

#11 NarcissisticNumbers solution and test case.
  src/zulqer/narcissisticNumbers/__tests__/index.test.ts
  src/zulqer/narcissisticNumbers/index.ts
Labels: task

#23 Created issue templates for Feature request, Bug report, New Assignment.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new-assignment.md
Labels: enhancement

#16 Narcissistic numbers printer implementation
  src/rajasekhar/narcissistic/index.ts
  src/rajasekhar/narcissistic/narcissistic.test.ts
  src/rajasekhar/narcissistic/narcissistic.ts
Labels: task

#14 Completed assignment #8 - Group people data based on their cities
  src/praveen/cityBasedGroup.test.ts
  src/praveen/cityBasedGroup.ts
Labels: task

#13 Solution for Assignment #8 - Group people data based on their cities
  src/rajasekhar/groupPeople/groupPeople.test.ts
  src/rajasekhar/groupPeople/groupPeople.ts
  src/rajasekhar/groupPeople/index.ts
Labels: task

#12 Added solutions for finding narcissistic numbers for the given range
  src/praveen/narcissistic.test.ts
  src/praveen/narcissistic.ts
Labels: task

#20 Added solution for Assignment #17 - Find the final direction facing of the vehicle at the end of the journey
  src/praveen/vehicleDirection.test.ts
  src/praveen/vehicleDirection.ts
Labels: task

#30 Fixed failing of unit tests in PR#20
  src/praveen/vehicleDirection.test.ts
Labels: bugfix

#26 Added Solution for Finding final direction of the vehicle assignment #17
  src/karthik/FindFinalDirectionOFVehicle/data.ts
  src/karthik/FindFinalDirectionOFVehicle/findFinalDirectionOfVehicle.spec.ts
  src/karthik/FindFinalDirectionOFVehicle/findFinalDirectionOfVehicle.ts
Labels: task
